package com.podmev.portuguese.engine.conjugator.analytic

object IrregularVerbs {
    const val SER = "ser"
    const val ESTAR = "estar"
    const val IR = "ir"
    const val TER = "ter"
    const val HAVER = "haver"
    const val FAZER = "fazer"
    const val DIZER = "dizer"
    const val PODER = "poder"
    const val VER = "ver"
    const val DAR = "dar"
    const val SABER = "saber"
    const val VIR = "vir"
    const val QUERER = "querer"
    const val OUVIR = "ouvir"
    const val PEDIR = "pedir"
    const val LER = "ler"
    const val POR = "pôr"
    const val TRAZER = "trazer"
    const val PERDER = "perder"
    const val DORMIR = "dormir"
    const val SUBIR = "subir"
    const val FUGIR = "fugir"
    const val RIR = "rir"
}